"""Register built-in semantic transformation contracts.

Extended Summary
----------------
This private module owns the declarative transformation vocabulary used by
the built-in certification handshakes. Registration stays explicit and
idempotent.

Notes
-----
The public registration boundary lives in diffpes.certify.models.
"""

from beartype.typing import Any, Tuple

from diffpes.types import (
    TransformationContract,
    make_transformation_contract,
)

from .registry import list_transformations, register_transformation


def _register_transformations() -> None:
    """PRIVATE: Register built-in semantic and information-loss
    contracts.

    Notes
    -----
    Builds the full tuple of built-in transformation contracts. Covers
    amplitude, band, resolution, normalization, k-space, kinematics,
    polarization, geometry, and tight-binding transformations. Then
    registers only the identity-version pairs that
    :func:`~.registry.list_transformations` does not already report.
    The skip step makes repeated registration idempotent against the
    append-only registry.
    """
    contract: Any
    contracts: Tuple[TransformationContract, ...] = (
        make_transformation_contract(
            "org.diffpes.transform.amplitude.intensity",
            "1.0.0",
            requires=("complex_photoemission_amplitude",),
            produces=("arpes_intensity",),
            preserves=("energy_reference", "momentum_coordinates"),
            destroys=("overall_matrix_element_phase",),
            invalidates_claims=("claim.amplitude.phase_recoverable",),
        ),
        make_transformation_contract(
            "org.diffpes.transform.band.incoherent_sum",
            "1.0.0",
            requires=("band_resolved_intensity",),
            produces=("summed_intensity",),
            preserves=("energy_reference", "momentum_coordinates"),
            destroys=("band_component_attribution",),
            invalidates_claims=("claim.band.attribution_preserved",),
        ),
        make_transformation_contract(
            "org.diffpes.transform.resolution.energy_voigt",
            "1.0.0",
            requires=("unbroadened_spectrum",),
            produces=("energy_broadened_spectrum",),
            preserves=("energy_reference", "momentum_coordinates"),
            introduces=("finite_energy_resolution",),
            destroys=("unresolved_energy_information",),
            invalidates_claims=("claim.spectrum.unbroadened",),
        ),
        make_transformation_contract(
            "org.diffpes.transform.normalization.zscore",
            "1.0.0",
            requires=("absolute_intensity",),
            produces=("standardized_intensity",),
            preserves=("energy_reference", "momentum_coordinates"),
            introduces=("dimensionless_standardization",),
            destroys=("absolute_intensity_calibration",),
            invalidates_claims=("claim.intensity.absolute_calibration",),
        ),
        make_transformation_contract(
            "org.diffpes.transform.self_energy.kk_causal",
            "1.0.0",
            requires=(
                "retarded_imaginary_self_energy",
                "declared_relative_energy_domain",
                "declared_subtraction_point",
                "serialized_power2_tail_coordinates",
            ),
            produces=("complex_retarded_self_energy",),
            preserves=(
                "relative_energy_reference",
                "self_energy_parameter_identity",
                "retarded_imaginary_sign",
            ),
            introduces=(
                "once_subtracted_kramers_kronig_real_part",
                "matrix_free_cell_integrated_principal_value",
                "smooth_mode_piecewise_cubic_core",
                "grid_mode_piecewise_linear_hat_core",
                "uniform_even_4096_node_default",
                "kk_selection_domain_minus8_plus8_ev",
                "kk_phase_aligned_integer_cell_domain_extension",
                "power2_tail_gauss_legendre_256_per_side",
                "trusted_interval_two_cell_margin",
                "direct_query_evaluation_without_interpolation",
                "kk_pair_mixed_bound_atol_2e_8_ev_rtol_1e_6",
                "kk_refinement_bounds_value_2e_6_ev_derivative_2e_5_jvp_2e_5_ev",
                "kk_tail_refinement_value_derivative_bound_1e_13",
                "kk_wigner_min_order_1p4_base_error_1e_5_ev",
                "faddeeva_upper_half_plane_closed_radius_1e8",
                "voigt_shared_faddeeva_guard",
                "voigt_zero_width_endpoints_value_only",
            ),
            invalidates_claims=(
                "claim.self_energy.imaginary_only",
                "claim.kk.query_window_defines_domain",
                "claim.kk.truncated_tail",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.spectral.resolvent",
            "1.0.0",
            requires=(
                "complex_hermitian_hamiltonian_relative_to_fermi",
                "complex_retarded_self_energy",
                "complex_transition_source",
                "strictly_positive_regulator",
            ),
            produces=("intrinsic_spectral_intensity",),
            preserves=(
                "relative_energy_reference",
                "degenerate_subspace_unitary_gauge",
                "outgoing_channel_incoherent_reduction",
            ),
            introduces=(
                "complex128_resolvent_linear_solve",
                "degeneracy_safe_hamiltonian_gradient",
                "scalar_retarded_self_energy_broadening",
                "hermitian_relative_tolerance_1e_12",
                "positive_regulator_default_1e_4_ev",
                "checkpointed_nested_k_omega_scan",
                "static_padded_256k_512omega_schedule",
                "static_k_chunk_32_omega_chunk_32",
                "explicit_nonempty_n_out_source_axis",
                "independent_scalar_rhs_solve_before_sum",
                "xla_memory_analysis_allocation_authority",
                "registered_spinless_solve_tape_1p5x_ceiling",
                "one_compile_per_padded_schedule",
            ),
            destroys=("overall_transition_source_phase",),
            invalidates_claims=(
                "claim.spectral.raw_eigenvector_gauge_observable",
                "claim.spectral.instrument_broadened",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.occupation.fermi_at_omega",
            "1.0.0",
            requires=(
                "intrinsic_spectral_intensity",
                "sampled_relative_energy",
                "strictly_positive_temperature",
            ),
            produces=("occupied_intrinsic_spectral_intensity",),
            preserves=(
                "relative_energy_reference",
                "sampled_energy_axis",
                "momentum_coordinates",
            ),
            introduces=("fermi_dirac_occupation_at_sampled_energy",),
            invalidates_claims=(
                "claim.occupation.evaluated_at_band_eigenvalue",
                "claim.spectral.instrument_broadened",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.kz.wrapped_lorentzian_integral",
            "1.0.0",
            requires=(
                "normal_reciprocal_covariant_full_integrand",
                "dimensionless_surface_fractional_kz_nodes",
                "exact_finite_energy_inner_potential_center",
                "positive_intensity_mean_free_path_angstrom",
                "primitive_surface_cell",
            ),
            produces=("kz_broadened_intrinsic_spectral_intensity",),
            preserves=(
                "relative_energy_reference",
                "surface_parallel_momentum",
                "normal_integration_coordinate_reciprocal_invariance",
                "fixed_parallel_and_outgoing_final_momenta",
                "hamiltonian_spectral_source_gauge_covariance",
                "physical_surface_repeated_zone_matrix_element_contrast",
                "constant_observable_unit_mass",
            ),
            introduces=(
                "wrapped_cauchy_analytic_bin_masses",
                "gauge_covariant_surface_reciprocal_folding",
                "gamma_hwhm_one_over_two_mean_free_path",
                "exact_finite_omega_kz_center",
                "fixed_surface_fractional_node_schedule",
                "g6_calibrated_n_kz_2048_or_explicit_caller_recalibration",
                "no_crop_renormalization_or_finite_image_sum",
                "checkpointed_node_local_lax_scan",
                "single_k_by_energy_accumulator",
                "no_complete_all_node_carrier",
            ),
            destroys=("resolved_bulk_kz_attribution",),
            invalidates_claims=(
                "claim.kz.sharp_direct_distribution",
                "claim.kz.coherent_slab_depth_sum",
                "claim.kz.crop_normalized_lorentzian",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.kz.photon_energy_scan",
            "1.0.0",
            requires=(
                "single_domain_pre_detector_intensity_program",
                "sampled_photon_energy_axis",
                "exact_finite_energy_inner_potential_kinematics",
            ),
            produces=("pre_detector_photon_energy_scan",),
            preserves=(
                "relative_energy_reference",
                "surface_parallel_momentum",
                "sampled_photon_energy_axis",
                "explicit_hamiltonian_derivative_authority",
            ),
            introduces=(
                "photon_energy_lax_scan",
                "finite_omega_kinematics_per_scan_sample",
                "elementwise_photon_energy_gradients",
                "flat_auxiliary_memory_beyond_returned_scan",
                "no_five_point_photon_energy_interpolation",
            ),
            invalidates_claims=(
                "claim.kz.fermi_level_center_broadcast_over_energy",
                "claim.kz.scan_includes_detector_response",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.detector.source_density_map",
            "1.0.0",
            requires=(
                "self_describing_source_density",
                "registered_sample_cartesian_frame",
                "experiment_geometry",
                "explicit_detector_calibration",
            ),
            produces=("detector_native_coordinate_density",),
            preserves=(
                "relative_energy_reference",
                "in_aperture_integrated_flux",
                "domain_identity_until_detector_space_mixture",
            ),
            introduces=(
                "active_zyz_domain_rotation",
                "active_sample_to_laboratory_azimuth_rotation",
                "projected_rotation_absolute_determinant_density_factor",
                "analytic_detector_inverse_jacobian",
                "four_point_gauss_legendre_finite_volume_map",
                "signed_diagonal_antidiagonal_boundary_seam_splitting",
                "clamped_linear_exterior_half_source_cells",
                "explicit_boundary_loss_captured_fraction",
                "general_rotation_strict_source_enclosure",
                "general_rotation_four_vs_eight_node_convergence",
                "enclosed_smooth_interior_coordinate_derivative_only",
                "slit_line_density_integrated_over_declared_v_aperture",
            ),
            destroys=("source_grid_sample_identity",),
            invalidates_claims=(
                "claim.detector.source_array_is_detector_raster",
                "claim.detector.target_inferred_from_source_extrema",
                "claim.detector.boundary_loss_renormalized",
                "claim.detector.general_rotation_boundary_intersection_certified",
                "claim.detector.general_rotation_support_crossing_accepted",
                "claim.detector.coordinate_map_topology_switch_differentiable",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.instrument.transmission_fixed_domain",
            "1.0.0",
            requires=(
                "true_kinetic_energy",
                "transmission_raw_slopes",
                "fixed_transmission_calibration_domain",
            ),
            produces=("transmission_weighted_detector_density",),
            preserves=(
                "detector_native_coordinates",
                "relative_energy_reference",
                "calibration_domain_mean_response",
            ),
            introduces=(
                "monotone_integrated_bernstein_log_response",
                "softplus_slope_coordinates",
                "fixed_64_point_gauss_legendre_normalization",
                "fixed_domain_mean_one_response",
                "caller_crop_invariant_transmission",
            ),
            invalidates_claims=(
                "claim.instrument.transmission_normalized_on_query_crop",
                "claim.instrument.transmission_applied_after_resolution",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.instrument.native_detector_resolution",
            "1.0.0",
            requires=(
                "detector_native_coordinate_density",
                "explicit_detector_bin_edges",
                "positive_native_fwhm_widths",
            ),
            produces=("native_resolution_broadened_detector_density",),
            preserves=(
                "detector_coordinate_units",
                "relative_energy_reference",
                "finite_window_flux_accounting",
            ),
            introduces=(
                "piecewise_constant_finite_volume_psf",
                "analytic_gaussian_bin_integrals",
                "separable_native_u_v_energy_resolution",
                "fwhm_to_sigma_single_owner_conversion",
                "boundary_loss_without_row_renormalization",
            ),
            destroys=("sub_psf_detector_structure",),
            invalidates_claims=(
                "claim.instrument.cartesian_k_psf_is_native_angular_psf",
                "claim.instrument.boundary_flux_preserved_by_renormalization",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.detector.expected_counts",
            "1.0.0",
            requires=(
                "post_resolution_detector_density",
                "detector_effects_parameters",
                "explicit_native_bin_volumes",
            ),
            produces=("detector_expected_counts",),
            preserves=(
                "detector_channel_identity",
                "native_detector_bin_identity",
                "nonnegative_rate_domain",
            ),
            introduces=(
                "softmax_detector_space_domain_mixture",
                "nonnegative_detector_background",
                "volume_mean_one_detector_sensitivity",
                "explicit_exposure_and_native_bin_volume",
                "optional_calibrated_post_count_response",
                "explicit_poisson_or_fixed_total_acquisition_mode",
            ),
            destroys=("pre_count_detector_density_units",),
            invalidates_claims=(
                "claim.detector.source_space_domain_mixture",
                "claim.detector.omitted_native_bin_volume",
                "claim.detector.display_normalization_is_likelihood",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.kspace.fractional_cartesian",
            "1.0.0",
            requires=(
                "fractional_reciprocal_coordinates",
                "reciprocal_lattice_basis",
            ),
            produces=("cartesian_reciprocal_coordinates",),
            preserves=(
                "physical_wavevector",
                "convention.reciprocal_basis_rows",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.kinematics.detector_angle_kpar",
            "1.0.0",
            requires=(
                "detector_angles",
                "photoelectron_kinetic_energy",
                "sample_detector_geometry",
            ),
            produces=("parallel_momentum",),
            preserves=(
                "photoelectron_direction",
                "convention.detector_slit_frame",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.kinematics.inner_potential",
            "1.0.0",
            requires=(
                "photoelectron_kinetic_energy",
                "parallel_momentum",
                "inner_potential",
            ),
            produces=("surface_normal_momentum",),
            preserves=(
                "complex_evanescent_branch",
                "convention.positive_kz_branch",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.polarization.lab_polarization_to_sample",
            "1.0.0",
            requires=(
                "laboratory_polarization",
                "sample_orientation",
            ),
            produces=("sample_frame_polarization",),
            preserves=(
                "polarization_norm",
                "polarization_helicity",
                "optical_phase",
                "fixed_beam_across_detector_pixels",
                "convention.sample_orientation_inverse",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.geometry.detector_axis_to_sample",
            "1.0.0",
            requires=(
                "detector_frame_axis",
                "detector_orientation",
                "sample_orientation",
            ),
            produces=("sample_frame_detector_axis",),
            preserves=(
                "axis_norm",
                "detector_axis_identity",
                "convention.detector_to_lab_then_lab_to_sample",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.tightb.bloch_basis_position",
            "1.0.0",
            requires=(
                "validated_hermitian_closed_hopping_list",
                "exact_integer_hopping_cells",
                "basis_fractional_positions",
                "fractional_reciprocal_coordinates",
            ),
            produces=("complex_hermitian_bloch_hamiltonian",),
            preserves=(
                "energy_reference",
                "fractional_reciprocal_coordinates",
                "orbital_spin_basis",
            ),
            introduces=("convention.bloch.basis_position_gauge",),
            destroys=("real_space_hopping_record_attribution",),
            invalidates_claims=(
                "claim.tightb.single_k_real_space_hoppings_recoverable",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.tightb.dos_gaussian",
            "1.0.0",
            requires=(
                "band_eigenvalues",
                "normalized_kpoint_weights",
                "energy_axis",
                "positive_gaussian_width",
            ),
            produces=("gaussian_broadened_density_of_states",),
            preserves=(
                "energy_reference",
                "integrated_state_count",
            ),
            introduces=("finite_gaussian_energy_resolution",),
            destroys=(
                "delta_resolved_spectral_information",
                "kpoint_resolved_attribution",
                "band_resolved_attribution",
            ),
            invalidates_claims=(
                "claim.dos.delta_resolved",
                "claim.dos.kpoint_attribution_preserved",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.tightb.eigensystem_fixed_group",
            "1.0.0",
            requires=("complex_hermitian_bloch_hamiltonian",),
            produces=(
                "sorted_band_eigenvalues",
                "degeneracy_safe_eigensystem",
                "fixed_group_gauge_invariant_observable",
            ),
            preserves=(
                "energy_reference",
                "fractional_reciprocal_coordinates",
                "orbital_spin_basis",
                "degenerate_group_subspace",
            ),
            introduces=(
                "regularized_eigenvector_differential",
                "fixed_group_gauge_invariance",
            ),
            destroys=(
                "individual_eigenvector_phase",
                "degenerate_subspace_basis_choice",
            ),
            invalidates_claims=(
                "claim.band.individual_eigenvector_phase_observable",
                "claim.band.degenerate_sorted_band_derivative",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.tightb.filling_fermi_level",
            "1.0.0",
            requires=(
                "band_eigenvalues",
                "normalized_kpoint_weights",
                "target_filling",
                "positive_electronic_temperature",
            ),
            produces=("finite_temperature_fermi_level",),
            preserves=(
                "energy_reference",
                "target_filling_constraint",
            ),
            introduces=(
                "fermi_dirac_occupation",
                "implicit_root_differential",
            ),
            destroys=(
                "band_resolved_attribution",
                "kpoint_resolved_attribution",
                "full_spectrum_recoverability",
            ),
            invalidates_claims=(
                "claim.fermi_level.full_band_structure_recoverable",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.tightb.depth_carrier",
            "1.0.0",
            requires=(
                "validated_optional_orbital_depths_angstrom",
                "tight_binding_model",
            ),
            produces=("diagonalized_bands_with_optional_orbital_depths",),
            preserves=(
                "depth_values_exactly",
                "depth_ordering",
                "depth_units_angstrom",
                "bulk_none_sentinel",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.tightb.slab_surface",
            "1.0.0",
            requires=(
                "validated_bulk_tight_binding_model",
                "primitive_miller_index",
                "frozen_slab_topology",
                "exact_integer_real_space_cells",
            ),
            produces=(
                "finite_open_slab_model",
                "orbital_depths_angstrom",
                "slab_construction_provenance",
            ),
            preserves=(
                "bulk_parameter_identity",
                "surface_translation_symmetry",
                "basis_position_gauge",
                "wannier_operator_sidecar",
            ),
            introduces=(
                "surface_cartesian_frame",
                "open_normal_boundary",
                "top_surface_depth_origin",
            ),
            destroys=("normal_translation_symmetry",),
            invalidates_claims=(
                "claim.slab.normal_bloch_momentum_observable",
            ),
        ),
        make_transformation_contract(
            "org.diffpes.transform.tightb.surface_projection",
            "1.0.0",
            requires=(
                "orbital_depths_angstrom",
                "positive_intensity_escape_length_angstrom",
                "diagonalized_slab_eigenvectors",
                "registered_isolated_band_groups",
            ),
            produces=(
                "surface_resolved_band_weights",
                "fixed_group_surface_traces",
            ),
            preserves=(
                "complete_group_unitary_gauge",
                "eigenvector_phase_gauge",
                "intensity_escape_length_convention",
            ),
            introduces=("exponential_intensity_depth_weight",),
        ),
    )
    existing: set[Tuple[str, str]] = {
        (item.transformation_id, item.transformation_version)
        for item in list_transformations()
    }
    for contract in contracts:
        key: Tuple[str, str] = (
            contract.transformation_id,
            contract.transformation_version,
        )
        if key not in existing:
            register_transformation(contract)


__all__: list[str] = []
